### ISSUE TITLE
Възможно ли е да работи с Kodi simple PVR client

### ISSUE THREAD

**Issue by svilenstefanov** [sgloutnikov/NeterraProxy#10]
Здравейте,

Работи прекрасно на Amazon Fire TV stick и Perfect player.
Опитвам се да го накарам да работи с Kodi / DMBC. PVR e Ok - виждам списък с каналите но при избор не тръгват. Опитах да сменям Render method настройката, но и това не помогна.

Някакви идеи какъв може да е проблема ? 

Поздрави

**Comment by sgloutnikov** [comment]
Да, би трябвало да работи и с Kodi IPTV Simple. Преди време когато го ползвах за друг IPTV доставчик трябваше да се включи тази настройка: Settings > Service settings > Control > allow remote control via HTTP.

![settings](https://user-images.githubusercontent.com/2321958/33633199-d44832d8-d9c4-11e7-9d5d-cde289b3e1be.jpg)

**Comment by svilenstefanov** [comment]
Мерси,

Ще опитам макар че не виждам как тази настройка има отношение към ИПТВ

Поздрави


Svilen Stefanov


On Tue, Dec 5, 2017 at 10:04 PM, Stefan Gloutnikov <notifications@github.com

**Comment by sgloutnikov** [comment]
Сега го пробвах на Коди 17.6 с PVR IPTV Simple Client и тръгна всичко без проблем. Има ли успех при теб?
