### ISSUE TITLE
Can't login. Neterra.tv website changes.

### ISSUE THREAD

**Issue by sgloutnikov** [sgloutnikov/NeterraProxy#11]
Edit: Fixed in [1.3.0](https://github.com/sgloutnikov/NeterraProxy/releases/tag/v1.3.0).

**Comment by ohliuw** [comment]
Yup, not working on Firetv

**Comment by sgloutnikov** [comment]
Fixed version should be released in a few hours when I get home :)

**Comment by sgloutnikov** [comment]
Fixed in [1.3.0](https://github.com/sgloutnikov/NeterraProxy/releases/tag/v1.3.0).

**Comment by sgloutnikov** [comment]
Fixed in cc6ba2c1c7ee449b9972089a0b3ba14d6f329624
