### ISSUE TITLE
Merge Live & VOD playlist into one?

### ISSUE THREAD

**Issue by sgloutnikov** [sgloutnikov/NeterraProxy#12]
Merge the two playlists into one. Decide from the URL parameters if live or VOD. 

- VOD usable on single playlist clients like Kodi IPTV Simple Client.
- Less typing during setup / easier access.

**Comment by vaipar03** [comment]
Zdraveite az imam problem s vod zapisite ne se updaitvat posledniat zapis e ot 5/4/18

**Comment by sgloutnikov** [comment]
Сега проверих при мен с най-новата версия (1.5.2) и записите заредиха без проблем до вчера (Шоуто на Слави и Господари на Ефира).
