### ISSUE TITLE
Not working again?

### ISSUE THREAD

**Issue by ohliuw** [sgloutnikov/NeterraProxy#13]
Can’t play any channel on firetv as of today?

**Comment by sgloutnikov** [comment]
Сега проверих при мен няколко канала на живо и работеха. v1.4.1 с Perfect Player.

**Comment by ohliuw** [comment]
Странно, не работи с моя абонамент, но работи с абонамента на мой приятел? Моят абонамент беше подновен преди няколко дена и нямам никакви проблеми да гледам от браузер?

**Comment by ohliuw** [comment]
Упс, сега забелязах, че съм със стара версия

**Comment by ohliuw** [comment]
Пак не работи с моя акаунт?

**Comment by sgloutnikov** [comment]
Провери дали плейър-а е HTML5 na http://www.neterra.tv/profile/player. Другото което е дали потребитела и паролата в проксито са 1:1 със тези в които се влиза в сайт-а.
