### ISSUE TITLE
VOD list is not updating ?

### ISSUE THREAD

**Issue by asus1200** [sgloutnikov/NeterraProxy#19]
Има ли проблем с VOD записите защото не се ъпдейтват, нямам идея от кога защото от началото на лятото не съм ползвал тази функция. Например няма ги новите серии на Откраднат живот от тази седмица. Даже си изтрих някой от фаворитите (любими предавания) от профила в на Нетера сайта и добавих нови, но никаква промяна в perfect Player-a...с последната версия и на проксито и на плеъра съм. Проблемът е на 2-та ми  Андроид ТВ бокса както и на телефона ми...

**Comment by sgloutnikov** [comment]
Не бях гледал на запис нещо и не бях забелязъл. Благодаря за известието! :)

Нетера са правили леки промени по сайта и проксито не можеше да прочита предаванията на запис правилно. Преди малко пуснах версия 1.5.5 която оправи нещата при мен, надявам се че и за всички. Има ли успех с нея?

Друго нещо ново което забелязах с Perfect Player и предаванията на запис е че за да може да се превъртат напред/назад трябва да е маркирана отметката VOD където се вписва плейлиста. Има и там някакви промени. Преди с FireTV не беше нужно да слагам отметката VOD и Perfect Player си разбираше че не е на живо канала. Сега ще е нужна просто още една стъпка да се влезе във VOD подсекцията и от там да се стартират предавания на запис--описано е в Wiki страницата по-подробно.

**Comment by asus1200** [comment]
Благодаря много за светкавичната реакция - записаните предавания се обновяват нормално ! Спомена за превъртането напред и назад, и аз да попитам : това не е възможно за каналите на живо (до 12 часа назад) нали, само през сайта им става...даже със сет-бокса ми още не става мисля...

**Comment by sgloutnikov** [comment]
Супер! За сега не става превъртането с каналите на живо. На сайт-а го правят чрез плейъра (clappr), но с Perfect Player не става. Ако ми остане време ще си поиграя, може да има как да стане...

**Comment by asus1200** [comment]
ok, и така твоята апликация върши страхотна работа !
