### ISSUE TITLE
Превъртане на каналите на живо

### ISSUE THREAD

**Issue by asus1200** [sgloutnikov/NeterraProxy#21]
Здравейте,
дали има нещо по въпроса с превъртането на каналите на живо , и въобще дали това е възможно...
Макар и без това, апликацията ви върши страхотна работа !
Благодаря !

**Comment by sgloutnikov** [comment]
За съжаление на този етап не виждам как може да стане като на сайта. Поне плейърите които съм виждал за Андроид (Perfect Player, Kodi, итн.) не са съвместими с типа стриймове на Нетера. На страницата си Нетера поддържат превъртането чрез плейъра който ползват (clappr). 

Когато натиснеш да превъртиш назад в плейъра на neterra.tv е все едно натискаш линк на уеб страница, задаваш заявка колко секунди 'Х' назад да върнеш, и сървъра ти връща стрийм към посочения канал който започва от 'Х' секунди назад. 

Аз какво правя в проксито е, събирам линковете за стриймовете на живо и ги компилирам в плейлист (.../playlist.m3u8). За момента, единственото което ми хрумва и евентуално мога да направя е да създавам няколко плейлист-а. Примерно група с канали които започват с 1 час назад, друга с 2 часа назад (тип times-hift каквото първо имаха Нетера) и така нататак. Може и да се направи да се конфигурират колко часа/минути всеки от тези нови плейлисти да връща. И така от момента в който се обнови плейлиста ще има различни плейлисти с time-shift канали. Мако играчка но така ще може и да си ги нагаждаш. Примерно знаеш че каквото искаш да гледаш по БНТ е почнало преди 125 минути, отиваш в проксито и попълваш плейлист 2 да започва с 125 минути назад, цъкаш save, отиваш в Perfect Player и даваш да обнови плейлистите--сега в плейлист 2 има канали които започват с 125 минути назад във времето но пак няма да може да се превъртат напред/назад... 

Не знам това колко ще е полезно обаче? Може да се пробвам да го направя някой ден...

**Comment by asus1200** [comment]
Мисля че е може би доста труд за малко хора като мен които го искат, но все пак мен би ме устройвало поне един един такъв плейлист да има съдържащ всички канали които могат да бъдат връщани назад и този плейлист да е изместен със точно 7 часа.
Или пък още по-добър вариант : плейлист от всички канали които позволят връщане назад но аз да мога задавам с колко часа/минути да ги върна (всичките разбира се),
Ако имаш време и ти се занимава аз ще тествам с удоволствие :)

**Comment by sgloutnikov** [comment]
Току що пуснах версия 1.6.0 със timeshift плейлист-а. Тествах каквото можах и уж всичко работи, но ще се радвам ако дадеш мнение също :) Най-вече дали са верни час/минути връщанията назад, защото ползвам каквото Нетера са предоставили. Канали като БНТ1, БТВ и Нова имат по 12 часа записи, но останалите са по 8 часа.

**Comment by asus1200** [comment]
От това което успях набързо да тествам мога да кажа че върши идеална работа плейлиста, пробвах и с изместване от 7 и от 9 часа назад. Мен ме устройва идеално, надявам се и други ще оценят по достойнство тази новост. Просто само мога да кажа дълбоко уважение за хора като теб които в свободното си време помагат на други и то безвъзмездно ! 
Ако забележа нещо специално относно новия плейлист пак ще пиша, но засега си е просто супер !

**Comment by asus1200** [comment]
Тimeshift плейлист върши идеална работа ! Благодаря !
