### ISSUE TITLE
Каналите не работят от днес най-вероятно ....

### ISSUE THREAD

**Issue by asus1200** [sgloutnikov/NeterraProxy#24]
Здравейте, сега забелязах че каналите не се стартират...дали е свързано с нова конфигурация или е нужна корекция в апликацията ?

**Comment by motionbug** [comment]
Have the same issue. My wife just let me know it’s not working...

**Comment by sgloutnikov** [comment]
http://neterra.tv changed today, probably that... will investigate tonight.

**Comment by sgloutnikov** [comment]
Fixed in [v1.6.1](https://github.com/sgloutnikov/NeterraProxy/releases/tag/v1.6.1)

**Comment by asus1200** [comment]
Супер, току що тествах с новата версия 1.6.1 и всичко си работи идеално ! Благодаря !
