### ISSUE TITLE
Not working on Mibox

### ISSUE THREAD

**Issue by ohliuw** [sgloutnikov/NeterraProxy#27]
V8.0.0

Kennel 4.9.54

Tried on 2 different Miboxes - it doesn’t display the « Ready to serve » message

**Comment by sgloutnikov** [comment]
Doesn't display the message or doesn't work? They run some custom Android maybe notification just doesn't work. I don't have any Miboxes so I can't test...

**Comment by ohliuw** [comment]
It doesn’t work (and I guess that’s why it doesn’t display the message). I
can enter the credentials and save the preferences, but it doesn’t seem to
work. Is there any log I can check?

**Comment by sgloutnikov** [comment]
Replace localhost with 127.0.0.1? [Wiki FAQ](https://github.com/sgloutnikov/NeterraProxy/wiki/%D0%A7%D0%B5%D1%81%D1%82%D0%BE-%D0%97%D0%B0%D0%B4%D0%B0%D0%B2%D0%B0%D0%BD%D0%B8-%D0%92%D1%8A%D0%BF%D1%80%D0%BE%D1%81%D0%B8)

**Comment by sgloutnikov** [comment]
Closing this, reopen if more info available.
