### ISSUE TITLE
Програмата на някои канали

### ISSUE THREAD

**Issue by asus1200** [sgloutnikov/NeterraProxy#30]
Забелязах че липсва програмата на 4-те канала на Max Sport но пък я има ако се отвори уеб страницата на Нетера или се гледа през техното сетбокс устройство...това проблем на проксито ли е или на РerfectPlayer...
Благодаря за услията които полaгате !

**Comment by sgloutnikov** [comment]
Да, просто за сега не са добавени новите канали към справочника... Aко ми остане време преди празниците ще погледна. Програмата се дърпа от друго място а не от нетера за това се получават разминавания когато добавят и махат канали.

**Comment by sgloutnikov** [comment]
Max Sport явно го няма за САЩ и не ги виждам в списъка с канали при мен...

**Comment by asus1200** [comment]
И да добавя че от вчера липсва програмата изцяло на всички канали...

**Comment by sgloutnikov** [comment]
Има промени при източника които скоро трябва да бъдат оправени.

**Comment by sgloutnikov** [comment]
Fixed in 91cff8e5ed62ad43278384d387582ab88a8a7b86 v1.6.3
